### ISSUE TITLE
Abandon protobuf for JSON?

### ISSUE THREAD

**Issue by irth** [irth/im_client_py#3]
I think protobuf makes it hard to allow for extending the base spec, e.g. IRC users have just their nicks and realnames, but for example on Facebook or Jabber you can have much more data.
I don't think I should limit plugins by specifying exact data structures, there should be a basic set of properties for every object type (like, user, message) and plugins should be able to extend on that.

**Comment by irth** [comment]
Actually, JSON-RPC maybe.

**Comment by irth** [comment]
It seems like JSON-RPC allows for two way communication. I guess that's the way to go.

**Comment by Bravo555** [comment]
Good idea, m8

**Comment by Bravo555** [comment]
What an unpleasant person to work with. I do not recommend this developer.

**Comment by irth** [comment]
I'm going to use JSON-RPC encoded as Netstrings (because they are simple). I've already started rewriting the code.

**Comment by irth** [comment]
I've made a class for RPC connection (5eb5980fb70e21f9d404b0587ab48cce12bf2373), what's left is to make the server use it.
